"""Golden test for the channel maps.

Every FERS/DRS tower assignment and every auxiliary-channel lookup is rendered
to one canonical text file, tests/reference/channel_maps.txt, which is committed
alongside the code. A refactor that is meant to preserve behaviour must leave
this file untouched; a deliberate map change shows up as a reviewable diff.

    python3 tests/test_channel_maps.py            # check (also runs under pytest)
    python3 tests/test_channel_maps.py --update   # accept the current maps
"""
import difflib
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REFERENCE = os.path.join(REPO_ROOT, "tests", "reference", "channel_maps.txt")

# One run per era of both builders, plus the run ranges that have no map.
MAP_RUNS = [316, 571, 600, 700, 950, 1010, 1050, 1150, 1200, 1400,
            1650, 1710, 1750, 1850, 1900, 2000]

# Dense grid around every run boundary the auxiliary tables switch on.
AUX_RUNS = [300, 500, 582, 583, 600, 684, 685, 700, 900, 1100, 1169, 1170,
            1182, 1183, 1200, 1259, 1260, 1300, 1326, 1327, 1341, 1342, 1400,
            1599, 1600, 1650, 1699, 1700, 1701, 1763, 1764, 1800, 1823, 1824,
            1827, 1828, 1850, 1900, 1993, 1994, 2000]

AUX_ACCESSORS = [
    "build_time_reference_channels", "build_hodo_trigger_channels",
    "build_hodo_pos_channels", "get_hole_veto_channel",
    "get_downstream_muon_channel", "get_downstream_ttu_muon_channel",
    "get_pre_shower_channel", "get_cerenkov_counters", "get_mcp_channels",
    "get_service_drs_channels", "get_pid_channels",
]


def _num(value):
    """Render a coordinate identically whether it is an int or a float."""
    return f"{value:g}" if isinstance(value, (int, float)) else str(value)


def _channel_line(key, channel):
    parts = [key, f"ch={channel.channel_no}"]
    if hasattr(channel, "group_no"):
        parts.append(f"grp={channel.group_no}")
    parts += [f"x={_num(channel.i_tower_x)}", f"y={_num(channel.i_tower_y)}",
              f"cer={int(bool(channel.isCer))}",
              f"quartz={int(bool(channel.isQuartz))}"]
    for attr in ("is_amplified", "is6mm", "is_reference"):
        if hasattr(channel, attr):
            parts.append(f"{attr}={int(bool(getattr(channel, attr)))}")
    return " ".join(parts)


def _render_boards(builder, run):
    try:
        boards = builder(run)
    except Exception as exc:                       # unsupported eras must stay so
        return [f"  <raises {type(exc).__name__}>"]
    lines = [f"  board_order: {', '.join(boards)}"]
    for key, board in boards.items():
        lines += ["  " + _channel_line(key, ch) for ch in board.channels]
    return lines


def _render_value(value):
    if isinstance(value, dict):
        return "{" + ", ".join(f"{k}: {v}" for k, v in value.items()) + "}"
    if isinstance(value, list):
        return "[" + ", ".join(str(v) for v in value) + "]"
    return str(value)


def build_reference():
    """Render every map and lookup to the canonical text form."""
    os.chdir(REPO_ROOT)          # channel_map reads a few paths relative to it
    sys.path.insert(0, REPO_ROOT)
    import channels.channel_map as cm

    out = ["# Generated by tests/test_channel_maps.py -- do not edit by hand.",
           "# Regenerate with: python3 tests/test_channel_maps.py --update", ""]
    for run in MAP_RUNS:
        out.append(f"=== run {run} : FERS ===")
        out += _render_boards(cm.build_fers_boards, run)
        out.append(f"=== run {run} : DRS ===")
        out += _render_boards(cm.build_drs_boards, run)
    out.append("")
    for run in AUX_RUNS:
        out.append(f"=== run {run} : auxiliary ===")
        for name in AUX_ACCESSORS:
            try:
                rendered = _render_value(getattr(cm, name)(run))
            except Exception as exc:
                rendered = f"<raises {type(exc).__name__}>"
            out.append(f"  {name}: {rendered}")
    return "\n".join(out) + "\n"


def test_channel_maps_match_reference():
    """The built maps must match the committed reference exactly."""
    current = build_reference()
    with open(REFERENCE) as handle:
        expected = handle.read()
    if current != expected:
        diff = "".join(difflib.unified_diff(
            expected.splitlines(keepends=True), current.splitlines(keepends=True),
            fromfile="reference", tofile="current", n=1))
        raise AssertionError(
            "channel maps changed relative to tests/reference/channel_maps.txt.\n"
            "If the change is intended, rerun with --update and review the diff.\n\n"
            + diff[:20000])


if __name__ == "__main__":
    if "--update" in sys.argv:
        text = build_reference()
        os.makedirs(os.path.dirname(REFERENCE), exist_ok=True)
        with open(REFERENCE, "w") as handle:
            handle.write(text)
        print(f"wrote {REFERENCE} ({text.count(chr(10))} lines)")
    else:
        test_channel_maps_match_reference()
        print("channel maps match the reference")
